name: Build Windows runner image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build image
        run: docker build --tag windows-github-runner:test .
